#!/bin/sh

p=$(pgrep -fo $0)
[[ $$ != $p ]] && kill -TERM -$p

IFS=':'
files=$(find -L $PATH -maxdepth 1 -type f -executable | sed 's:.*/::' | sort -u)

run_term="echo \"${FMENU_TERM:-alacritty} -e sh -c {}\""
opts="--tiebreak=begin --bind='alt-enter:execute($run_term)+abort' $@"
command=$(echo ${files[@]} | fmenu "$opts")

[ -n "$command" ] && eval "$command"
