#!/bin/sh

input=$(mktemp -u --suffix .fmenu.input)
output=$(mktemp -u --suffix .fmenu.output)
mkfifo $input
mkfifo $output
chmod 600 $input $output

term=${FMENU_TERM:-st}
opts="$FMENU_TERM_DEFAULT_OPTS -c fmenu -t fmenu"
$term $opts -e sh -c "cat $input | \
  fzf --height=100% --no-info --reverse $@ | \
  tee $output" & disown

trap "kill $! 2>/dev/null; rm -f $input $output" EXIT

cat > $input
cat $output
